version: "3.3"
    
services:
  swbeefdb:
    image: ${MYSQLV} 
    volumes:
      - db_data:/bitnami/mysql/data
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USR}
      MYSQL_PASSWORD: ${MYSQL_PW}
    
  wordpress:
    depends_on:
      - swbeefdb
    image: ${WPV}
    volumes:
      - wp_data:/bitnami/wordpress
    ports:
      - '8000:8081'
      # - '4434:8443'
    restart: always
    environment:
      APACHE_HTTP_PORT_NUMBER: ${WPPORT}
      WORDPRESS_DATABASE_HOST: ${WP_DB_HOST}
      WORDPRESS_DATABASE_USER: ${WP_DB_USR}
      WORDPRESS_DATABASE_PASSWORD: ${WP_DB_PW}
      WORDPRESS_DATABASE_NAME: ${WP_DB_NAME}
      PHP_UPLOAD_MAX_FILESIZE: 512M

  adminer:
    image: ${PHPV}
    ports:
      - 8090:8080
    restart: always
    environment:  
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT}

volumes:
  db_data: {}
  wp_data: {}